import { FormEvent, useEffect, useRef, useState } from 'react'
import { ArrowUp, Bot, Check, ChevronRight, FileSearch, Lightbulb, LoaderCircle, ShieldAlert, Sparkles } from 'lucide-react'
import { api, post } from '../api'
import { Badge, PageHeader } from '../components'
import { Supplier } from '../types'

type Message={role:'user'|'assistant';content:string;model?:string}
const prompts=['올해 계약 종료 예정이면서 Risk HIGH인 업체 알려줘.','최근 평가가 급격히 하락한 업체를 찾아줘.','구매 의존도가 높은 공급업체와 대안을 분석해줘.','납기 준수율이 낮은 공급업체의 공통 위험요인을 알려줘.']
export default function AIAnalyst(){const [messages,setMessages]=useState<Message[]>([]);const [question,setQuestion]=useState('');const [busy,setBusy]=useState(false);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [selected,setSelected]=useState<string[]>([]);const end=useRef<HTMLDivElement>(null);useEffect(()=>{api<{items:Supplier[]}>('/api/v1/suppliers?limit=100').then(x=>setSuppliers(x.items))},[]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,busy]);async function ask(e?:FormEvent){e?.preventDefault();if(!question.trim()||busy)return;const q=question.trim();setQuestion('');setMessages(m=>[...m,{role:'user',content:q}]);setBusy(true);try{const r=await post<{answer:string;model:string}>('/api/v1/ai/analyze',{question:q,supplierIds:selected,mode:'supplier_analyst'});setMessages(m=>[...m,{role:'assistant',content:r.answer,model:r.model}])}catch(e){setMessages(m=>[...m,{role:'assistant',content:e instanceof Error?e.message:'분석 요청에 실패했습니다.'}])}finally{setBusy(false)}}
return <div className="page ai-page"><PageHeader eyebrow="AI supplier analyst" title="Vendra Intelligence" description="승인된 Vendra 데이터와 관리자가 연결한 OpenAI 호환 모델을 사용해 공급망을 분석합니다." actions={<Badge tone="purple"><Sparkles/>Grounded in Vendra data</Badge>}/><div className="ai-layout"><aside className="ai-context"><div><h3>분석 범위</h3><p>특정 공급업체를 선택하지 않으면 집계 질의로 처리합니다.</p></div><div className="context-list">{suppliers.slice(0,20).map(s=><button className={selected.includes(s.id)?'selected':''} onClick={()=>setSelected(x=>x.includes(s.id)?x.filter(i=>i!==s.id):[...x,s.id])} key={s.id}><span className="company-avatar">{s.name.slice(0,2)}</span><span><b>{s.name}</b><small>{s.riskLevel} · {s.grade||'미평가'}</small></span>{selected.includes(s.id)&&<Check/>}</button>)}</div><div className="privacy-note"><ShieldAlert/><span><b>데이터 보호</b>선택한 업무 데이터만 구성된 AI 엔드포인트로 전송됩니다.</span></div></aside><section className="chat"><div className="chat-scroll">{messages.length===0?<div className="chat-welcome"><div className="ai-orb"><Bot/><i/></div><p className="eyebrow">Ask Vendra</p><h2>공급망에 대해 무엇이든 물어보세요.</h2><p>계약, 비용, 품질, 평가와 위험 신호를 연결해 답합니다.</p><div className="prompt-grid">{prompts.map((p,i)=><button key={p} onClick={()=>setQuestion(p)}><span>{i===0?<FileSearch/>:i===1?<Sparkles/>:i===2?<Lightbulb/>:<ShieldAlert/>}</span><b>{p}</b><ChevronRight/></button>)}</div></div>:<div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}>{m.role==='assistant'&&<span className="bot-avatar"><Bot/></span>}<div>{m.content.split('\n').map((x,j)=><p key={j}>{x}</p>)}{m.model&&<small>{m.model} · Vendra grounded response</small>}</div></div>)}{busy&&<div className="message assistant"><span className="bot-avatar"><Bot/></span><div className="thinking"><LoaderCircle className="spin"/>계약, 평가, 리스크 신호를 분석하고 있습니다…</div></div>}<div ref={end}/></div>}</div><form className="chat-input" onSubmit={ask}>{selected.length>0&&<div className="selected-context"><span>{selected.length}개 공급업체 컨텍스트</span><button type="button" onClick={()=>setSelected([])}>모두 해제</button></div>}<div><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="예: A사와 B사의 가격·품질·납기 성과를 비교해줘" rows={2}/><button className="send" disabled={!question.trim()||busy}><ArrowUp/></button></div><small>AI 결과는 의사결정을 보조하며, 중요한 판단은 원본 데이터와 담당자 검토가 필요합니다.</small></form></section></div></div>}
