import { useCallback, useEffect, useState } from 'react'
import { Check, CheckCircle2, Clock3, FileCheck2, RotateCcw, X } from 'lucide-react'
import { api, date, money, post } from '../api'
import { Badge, Empty, Loading, Modal, PageHeader } from '../components'
import { statusTone } from '../status'

type Approval={id:string;objectType:string;objectId:string;status:string;currentStep:number;currentStepDefinition:{name?:string;role?:string};requestedBy?:string;createdAt:string;workflowName:string;number?:string;title?:string;amount?:number;supplierName?:string}
export default function Approvals(){const [items,setItems]=useState<Approval[]>();const [selected,setSelected]=useState<Approval>();const load=useCallback(()=>api<{items:Approval[]}>('/api/v1/approvals').then(x=>setItems(x.items)),[]);useEffect(()=>{void load()},[load]);if(!items)return <Loading/>;return <div className="page"><PageHeader eyebrow="Approval workspace" title="내 승인함" description="업무 맥락과 공급업체 리스크를 확인하고 승인, 반려 또는 보완 요청을 처리합니다."/><div className="approval-summary"><div><Clock3/><span><b>{items.length}</b>승인 대기</span></div><div><CheckCircle2/><span><b>—</b>이번 달 완료</span></div><div><RotateCcw/><span><b>—</b>보완 요청</span></div></div>{items.length?<div className="approval-layout"><div className="approval-list">{items.map(x=><button className={selected?.id===x.id?'active':''} onClick={()=>setSelected(x)} key={x.id}><span className="object-icon"><FileCheck2/></span><div><span><Badge tone={statusTone(x.status)}>{x.currentStepDefinition?.name||'승인 대기'}</Badge><small>{date(x.createdAt)}</small></span><b>{x.title||x.number}</b><p>{x.supplierName||'공급업체 미지정'} · {money(x.amount)}</p></div></button>)}</div><div className="approval-preview">{selected?<ApprovalDetail item={selected} onDone={()=>{setSelected(undefined);void load()}}/>:<Empty title="검토할 업무를 선택하세요" description="왼쪽 목록에서 승인 요청을 선택하면 상세 맥락을 표시합니다."/>}</div></div>:<Empty icon={<CheckCircle2/>} title="모든 승인 업무를 처리했습니다" description="현재 사용자에게 할당된 승인 대기 건이 없습니다."/>}</div>}
function ApprovalDetail({item,onDone}:{item:Approval;onDone:()=>void}){const [action,setAction]=useState<string>();const [comment,setComment]=useState('');const [busy,setBusy]=useState(false);async function submit(){if(!action)return;setBusy(true);try{await post(`/api/v1/approvals/${item.id}/actions`,{action,comment});onDone()}finally{setBusy(false)}}return <><div className="approval-detail-head"><div><p className="eyebrow">{item.workflowName}</p><h2>{item.title}</h2><span>{item.number} · {item.objectType}</span></div><Badge tone="warning">{item.currentStepDefinition.name||`단계 ${item.currentStep+1}`}</Badge></div><dl className="approval-data"><dt>공급업체</dt><dd>{item.supplierName||'—'}</dd><dt>금액</dt><dd>{money(item.amount)}</dd><dt>요청일</dt><dd>{date(item.createdAt)}</dd><dt>승인 역할</dt><dd>{item.currentStepDefinition.role||'지정 사용자'}</dd></dl><div className="approval-context"><h3>검토 체크포인트</h3><p><Check/>공급업체 거래상태 및 Risk 등급</p><p><Check/>예산과 계약금액의 정합성</p><p><Check/>첨부 문서 및 계약 조건</p></div><div className="approval-actions"><button className="button secondary" onClick={()=>setAction('return')}><RotateCcw/>보완 요청</button><button className="button danger" onClick={()=>setAction('reject')}><X/>반려</button><button className="button" onClick={()=>setAction('approve')}><Check/>승인</button></div>{action&&<Modal title={action==='approve'?'승인하시겠습니까?':action==='reject'?'반려하시겠습니까?':'보완을 요청하시겠습니까?'} onClose={()=>setAction(undefined)}><label className="field"><span>검토 의견</span><textarea rows={5} value={comment} onChange={e=>setComment(e.target.value)} placeholder="결정 사유 또는 요청사항을 남기세요."/></label><div className="form-actions"><button className="button secondary" onClick={()=>setAction(undefined)}>취소</button><button className={`button ${action==='reject'?'danger':''}`} disabled={busy} onClick={submit}>{busy?'처리 중…':'결정 확정'}</button></div></Modal>}</>}
